package com.photohunter.game.game

import android.content.Context
import android.media.AudioAttributes
import android.media.MediaPlayer
import android.media.SoundPool
import androidx.annotation.RawRes

/**
 * Background music + sound effects.
 *
 * Music uses two looping MediaPlayers' worth of state (one at a time) so the
 * menu and in-level tracks never overlap, and effects use SoundPool so several
 * can ring together (a found chime on top of the chapter fanfare).
 *
 * All audio is generated by tools/generate_audio.py - no downloaded media.
 */
class AudioController(private val context: Context) {

    private var music: MediaPlayer? = null
    private var currentTrack = 0

    private val pool: SoundPool = SoundPool.Builder()
        .setMaxStreams(6)
        .setAudioAttributes(
            AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_GAME)
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .build(),
        )
        .build()

    private val samples = HashMap<Int, Int>()

    var muted: Boolean = false
        private set

    fun preload(@RawRes vararg resIds: Int) {
        for (id in resIds) {
            if (!samples.containsKey(id)) {
                samples[id] = pool.load(context, id, 1)
            }
        }
    }

    fun playBgm(@RawRes trackRes: Int) {
        if (currentTrack == trackRes && music != null) return
        currentTrack = trackRes
        releaseMusic()
        if (muted) return
        music = MediaPlayer.create(context, trackRes)?.apply {
            isLooping = true
            setVolume(MUSIC_VOLUME, MUSIC_VOLUME)
            start()
        }
    }

    fun stopBgm() {
        currentTrack = 0
        releaseMusic()
    }

    fun playSfx(@RawRes resId: Int, volume: Float = 1f) {
        if (muted) return
        val sample = samples[resId] ?: return
        pool.play(sample, volume, volume, 1, 0, 1f)
    }

    fun setMuted(value: Boolean) {
        if (muted == value) return
        muted = value
        val player = music
        if (player != null) {
            player.setVolume(if (value) 0f else MUSIC_VOLUME, if (value) 0f else MUSIC_VOLUME)
        } else if (!value && currentTrack != 0) {
            playBgm(currentTrack)
        }
    }

    /** Called when the app leaves the foreground. */
    fun pause() {
        music?.takeIf { it.isPlaying }?.pause()
    }

    /** Called when the app returns to the foreground. */
    fun resume() {
        if (muted) return
        val player = music
        if (player != null) {
            if (!player.isPlaying) player.start()
        } else if (currentTrack != 0) {
            playBgm(currentTrack)
        }
    }

    fun release() {
        releaseMusic()
        pool.release()
    }

    private fun releaseMusic() {
        music?.run {
            try {
                if (isPlaying) stop()
            } catch (_: IllegalStateException) {
                // already stopped
            }
            release()
        }
        music = null
    }

    private companion object {
        const val MUSIC_VOLUME = 0.5f
    }
}
